spring:
  application:
    name: ${PROJECT_NAME}
    version: ${PROJECT_VERSION}
  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  # DB config
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

discodeit:
  storage:
    type: ${APP_STORAGE_TYPE:local} # local, s3
    local:
      root-path: ${APP_STORAGE_PATH:./data} # ${user.dir}/data
    aws:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
      s3Bucket: ${AWS_S3_BUCKET}
      s3Region: ${AWS_S3_REGION}
      s3PresignedUrlExpiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION}
  #  repository:
  #    type: file   # jcf | file
  #    file-directory: .discodeit


# /api-docs endpoint custom path
springdoc:
  api-docs:
    # OpenAPI 명세서 경로(JSON)
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    operations-sorter: alpha


# Actuator 엔드포인트 활성화 및 설정
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  info:
    env:
      enabled: true
  observations:
    annotations:
      enabled: true

#  http://localhost:8080/actuator/info
info:
  app:
    name: Discodeit
    version: 1.7.0
  java:
    version: 17
  spring-boot:
    version: 3.4.0
  datasource:
    url: ${DB_URL}
    driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    ddl-auto: ${spring.jpa.hibernate.ddl-auto}
  storage:
    type: ${discodeit.storage.type}
    path: ${discodeit.storage.local.root-path}
  multipart:
    max-file-size: ${spring.servlet.multipart.maxFileSize}
    max-request-size: ${spring.servlet.multipart.maxRequestSize}



# JWT 설정
jwt:
  access-token:
    secret: 25TsK+IZGYRUVYZa5GFsgwhhZKsJOwaiysuM9o9tkvk= #change-me-access-secret-for-dev-only
    exp: 900000        # 15분(ms)
  refresh-token:
    secret: thldHDIagbDTJ6WImb9d29vDigMJ+2bMnvTb/JGRMQ0= #change-me-refresh-secret-for-dev-only
    exp: 3600000       # 1시간(ms)

#  # Admin 서버 설정 정보 추가
#  boot:
#    admin:
#      client:
#        instance:
#          name: discodeit
