# 서버 포트
server:
  port: ${APP_PORT:8080}

# ─────────────────────────────────────────────
spring:
  # DB config
  datasource:
    driver-class-name: org.postgresql.Driver
  # JPA + Postgres 설정
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true     # 쿼리 로그 포맷 (정렬)
        highlight_sql: true  # 쿼리 로그 출력
  # SQL 스크립트 실행 여부 (script-based 기반 sql문)
  sql:
    init:
      mode: never  # 외부 DB도 실행

# ─────────────────────────────────────────────
# 로깅 설정
logging:
  level:
    root: info
    org.hibernate.sql: debug                #  = spring.jpa.show-sql: true  +  sql 이 실행된 시간 정보
    org.hibernate.orm.jdbc.bind: trace     # SQL에 바인딩된 실제 값을 보기 위해 설정
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: off # @ConditionalOnClass did not find required class 로그 숨기기
    org.springframework.boot.autoconfigure: warn
    org.springframework.cache: DEBUG
    org.springframework.data.redis.cache: DEBUG
# ─────────────────────────────────────────────
#  # Admin 서버 설정 정보 추가
#  boot:
#    admin:
#      client:
#        url: ${SPRING_BOOT_ADMIN_CLIENT_URL}